export const ADD_MAP_DATA_REQUEST = 'ADD_MAP_DATA_REQUEST'
export const ADD_MAP_DATA_SUCCESS = 'ADD_MAP_DATA_SUCCESS'
export const ADD_MAP_DATA_FAIL = 'ADD_MAP_DATA_FAIL'
export const GET_MAP_DATA_RESET = 'GET_MAP_DATA_RESET'

export const GET_MAP_DATA_REQUEST = 'GET_MAP_DATA_REQUEST';
export const GET_MAP_DATA_SUCCESS = 'GET_MAP_DATA_SUCCESS';
export const GET_MAP_DATA_FAIL = 'GET_MAP_DATA_FAIL';
