export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LIST_PROFILES_REQUEST = 'LIST_PROFILES_REQUEST';
export const LIST_PROFILES_SUCCESS = 'LIST_PROFILES_SUCCESS';
export const LIST_PROFILES_FAIL = 'LIST_PROFILES_FAIL';
export const LIST_PROFILES_RESET = 'LIST_PROFILES_RESET';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
export const UPLOAD_IMAGE_RESET = 'UPLOAD_IMAGE_RESET';

export const LIST_INVITATIONS_REQUEST = 'LIST_INVITATIONS_REQUEST';
export const LIST_INVITATIONS_SUCCESS = 'LIST_INVITATIONS_SUCCESS';
export const LIST_INVITATIONS_FAIL = 'LIST_INVITATIONS_FAIL';
export const LIST_INVITATIONS_RESET = 'LIST_INVITATIONS_RESET';

export const SEND_INVITATION_REQUEST = 'SEND_INVITATION_REQUEST';
export const SEND_INVITATION_SUCCESS = 'SEND_INVITATION_SUCCESS';
export const SEND_INVITATION_FAIL = 'SEND_INVITATION_FAIL';
export const SEND_INVITATION_RESET = 'SEND_INVITATION_RESET';
